name: WIP
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: knu/wip@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
